//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXCollectionView.h"
#import "_UXCollectionViewOverdraw-Protocol.h"

@class NSString;

@interface _UXCollectionView : UXCollectionView <_UXCollectionViewOverdraw>
{
}

+ (Class)documentClass;
@property(nonatomic) BOOL overdrawEnabled;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) NSUInteger hash;
@property(readonly) Class superclass;

@end

