//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXView.h"

#import "UXLayoutSupport-Protocol.h"

@class NSLayoutConstraint, NSString;

@interface _UXLayoutGuide : UXView <UXLayoutSupport>
{
    NSLayoutConstraint *_counterDimensionConstraint;
    NSLayoutConstraint *_dimensionConstraint;
    BOOL _horizontal;
    CDUnknownBlockType _lengthUpdateBlock;
}

@property(copy, nonatomic) CDUnknownBlockType lengthUpdateBlock; // @synthesize lengthUpdateBlock=_lengthUpdateBlock;
@property(nonatomic) BOOL horizontal; // @synthesize horizontal=_horizontal;
- (void)cxx_destruct;
- (void)_setUpDimensionConstraintWithLength:(double)arg1;
- (void)_setUpCounterDimensionConstraint;
@property(nonatomic) double length;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) NSUInteger hash;
@property(readonly) Class superclass;

@end

