//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UXView.h"

#import "_UXBarItemsContainer.h"

@class NSLayoutConstraint, NSMutableArray, NSString, NSView, UXImageView, UXNavigationBar, UXNavigationItem;

@interface _UXNavigationItemContainerView : UXView <_UXBarItemsContainer>
{
    UXImageView *_snaphotView;
    UXNavigationItem *_item;
    UXNavigationBar *_navigationBar;
    unsigned long long _state;
    NSMutableArray *_leftItemViews;
    NSView *_titleView;
    NSMutableArray *_rightItemViews;
    NSMutableArray *_addedConstraints;
    NSLayoutConstraint *_titleCenteringConstraint;
    NSView *_titleCenteringConstrainedTitleView;
    NSView *_titleCenteringTrackedView;
    NSView *_titleCenteringConstraintOwnerView;
}

+ (id)layoutContainerForItem:(id)arg1 navigationBar:(id)arg2;
@property(nonatomic) __weak NSView *titleCenteringConstraintOwnerView; // @synthesize titleCenteringConstraintOwnerView=_titleCenteringConstraintOwnerView;
@property(nonatomic) __weak NSView *titleCenteringTrackedView; // @synthesize titleCenteringTrackedView=_titleCenteringTrackedView;
@property(nonatomic) __weak NSView *titleCenteringConstrainedTitleView; // @synthesize titleCenteringConstrainedTitleView=_titleCenteringConstrainedTitleView;
@property(retain, nonatomic) NSLayoutConstraint *titleCenteringConstraint; // @synthesize titleCenteringConstraint=_titleCenteringConstraint;
@property(retain, nonatomic) NSMutableArray *addedConstraints; // @synthesize addedConstraints=_addedConstraints;
@property(retain, nonatomic) NSMutableArray *rightItemViews; // @synthesize rightItemViews=_rightItemViews;
@property(retain, nonatomic) NSView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) NSMutableArray *leftItemViews; // @synthesize leftItemViews=_leftItemViews;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(readonly, nonatomic) __weak UXNavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;
@property(readonly, nonatomic) UXNavigationItem *item; // @synthesize item=_item;
- (void)cxx_destruct;
- (void)_updateItemsViews:(id)arg1 withNewViews:(id)arg2;
- (void)setTitleCenteringTrackedView:(id)arg1 updateConstraints:(BOOL)arg2;
- (void)updateConstraints;
- (id)hitTest:(struct CGPoint)arg1;
- (void)viewDidMoveToWindow;
- (void)viewWillMoveToWindow:(id)arg1;
- (id)subviewsIntersectedWithViews:(id)arg1;
- (void)updateRightItemViewsAnimated:(BOOL)arg1;
- (void)updateLeftItemViewsAnimated:(BOOL)arg1;
- (void)_updateItemViews;
- (void)cancelTransistion;
- (void)prepareForTransistion;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

