//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



@class _UXSourceSplitView;

@protocol _UXSourceSplitViewDelegate <NSObject>
- (void)sourceSplitView:(_UXSourceSplitView *)arg1 didResizeMasterWidth:(double)arg2;
@end

