//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface _UXSourceUtilities : NSObject
{
}

+ (id)constraintWithItem:(id)arg1 attribute:(long long)arg2 equalToItem:(id)arg3 constant:(double)arg4;

@end

