//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import AppKit;

@class NSWindow, UXWindowController;

@interface UXViewControllerWindowTransition : NSViewControllerPresentationAnimatorObject
{
    UXWindowController *_windowController;
}

@property(retain) UXWindowController *windowController; // @synthesize windowController=_windowController;
- (void)cxx_destruct;
- (void)animateDismissalOfViewController:(id)arg1 fromViewController:(id)arg2;
- (void)animatePresentationOfViewController:(id)arg1 fromViewController:(id)arg2;
- (void)_windowWillClose:(id)arg1;
- (void)dealloc;
@property(readonly) NSWindow *window;

@end

